name: Run Selenium Tests

on:
  push:
    branches:
      - '**'

jobs:
  selenium-tests:
    name: Run Selenium Tests
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: uvlhub_root_password
          MYSQL_DATABASE: uvlhubdb_test
          MYSQL_USER: uvlhub_user
          MYSQL_PASSWORD: uvlhub_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e ./

      - name: Start Docker containers
        run: |
          scripts/start_docker_containers.sh sh

      - name: Wait for services to be ready
        run: |
          docker run --network host --rm alpine sh -c 'while ! nc -z localhost 3306; do sleep 1; done'
          docker run --network host --rm alpine sh -c 'while ! nc -z localhost 4444; do sleep 1; done'

      - name: Run Selenium tests
        run: |
          docker exec -i web_app_container rosemary selenium