FROM python:3.12-slim
        
WORKDIR /fakenodo

COPY app/fakenodo/ .

RUN pip install --no-cache-dir --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 5001

CMD ["flask", "run", "--debug", "--host=0.0.0.0", "--port=5001"]