"""empty message

Revision ID: 63858026b97d
Revises: 80b436cd6ef7
Create Date: 2024-11-23 14:39:04.110640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63858026b97d'
down_revision = '80b436cd6ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'community', ['community_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('community_id')

    # ### end Alembic commands ###
