"""empty message

Revision ID: 80b436cd6ef7
Revises: fc60c2b8b738
Create Date: 2024-11-23 13:15:32.392243

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80b436cd6ef7'
down_revision = 'fc60c2b8b738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members_association',
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('community_id', 'user_id')
    )
    op.drop_table('community_members')
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.drop_constraint('data_set_ibfk_3', type_='foreignkey')
        batch_op.drop_column('community_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('data_set_ibfk_3', 'community', ['community_id'], ['id'])

    op.create_table('community_members',
    sa.Column('community_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], name='community_members_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='community_members_ibfk_2'),
    sa.PrimaryKeyConstraint('community_id', 'user_id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('members_association')
    # ### end Alembic commands ###
