"""empty message

Revision ID: 97126b733799
Revises: 9ee0d851ea6b
Create Date: 2024-11-23 17:55:23.293093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97126b733799'
down_revision = '9ee0d851ea6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'community', ['community_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('community_id')

    # ### end Alembic commands ###
