"""empty message

Revision ID: fc60c2b8b738
Revises: 529ff873ae2f
Create Date: 2024-11-22 20:52:52.948495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc60c2b8b738'
down_revision = '529ff873ae2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.drop_constraint('data_set_ibfk_3', type_='foreignkey')
        batch_op.drop_column('community_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('data_set_ibfk_3', 'community', ['community_id'], ['id'])

    # ### end Alembic commands ###
