name: Update Coverage Badge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests and Generate Coverage Report
      run: |
        coverage run -m pytest
        coverage-badge -o coverage.svg

    - name: Commit and Push Badge
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add coverage.svg
        git commit -m "Update coverage badge"
        git push
